ci:
  autofix_commit_msg: "[pre-commit.ci] auto fixes from pre-commit.com hooks [dependabot skip]"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
        args: [--unsafe]
      - id: trailing-whitespace
      - id: check-toml
      - id: check-merge-conflict
      - id: end-of-file-fixer

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.2
    hooks:
      - id: ruff
      - id: ruff-format

  - repo: https://github.com/jackdewinter/pymarkdown
    rev: v0.9.13.4
    hooks:
      - id: pymarkdown
        exclude: ^.github/|CHANGELOG
        args: [-d, "MD046", scan]

  - repo: https://github.com/python-poetry/poetry
    rev: "1.6.1"
    hooks:
      - id: poetry-check
      # - id: poetry-lock
      - id: poetry-export
        args:
          [
            "--without-hashes",
            "-f",
            "requirements.txt",
            "-o",
            "requirements.txt",
            "--with",
            "dev",
          ]
