site_name: Markdown Changelog Generator
site_url: https://changelog.seapagan.net

theme:
  name: material
  palette:
    primary: light-blue
    accent: blue
  features:
    - navigation.footer
    - content.code.copy
    - content.code.annotate
    - navigation.tracking
    - navigation.indexes
    - navigation.prune
    - navigation.top
    - toc.follow
    # - navigation.expand
  icon:
    logo: material/history
  favicon: images/favicon.ico

extra:
  analytics:
    provider: google
    property: G-F151EK9LZX
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/seapagan
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/gnramsay_dev
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

copyright: © 2023-2024 Grant Ramsay (Seapagan)

hooks:
  - docs/hooks/google_style_notes.py

plugins:
  - search
  # - git-revision-date-localized:
  #     enable_creation_date: true
  - minify:
      minify_html: true
      minify_css: true
      minify_js: true
      htmlmin_opts:
        remove_comments: true
        remove_empty_space: true

repo_url: https://github.com/seapagan/github-changelog-md
repo_name: github-changelog-md

# edit these MARKDOWN extensions to your liking
markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.snippets
  - pymdownx.superfences
  - md_in_html
  - pymdownx.highlight:
      auto_title: false
  - attr_list
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - css/extra.css

nav:
  - Introduction: index.md
  - Installation: installation.md
  - Basic Usage: usage/basic.md
  - Advanced Usage:
      - "Configuration Options": usage/options.md
      - "Configuration File": usage/config_file.md
      - "Command Line Options": usage/cli_options.md
  - Todo List: todo.md
  - Contributing: contributing.md
  - Changelog: changelog.md
  - License: license.md
