name: Type Checking (ty)

on: [push, pull_request, workflow_dispatch]

jobs:
  ty:
    # uncomment the line before to disable this job if needed.
    # if: false
    name: ty
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Install uv
        uses: astral-sh/setup-uv@v10.0.1
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python
        run: uv python install 3.12

      - name: Run ty
        run: uv run ty check --output-format concise
